pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        echo echo "Here's the version of node:"
        sh 'node --version'
      }
    }
  }
}
